yl_company:
    resource: "@YLCompanyBundle/Resources/config/routing.yml"
    prefix:   /{_locale}/company
    requirements:
        _locale: en|fr|

yl_core_app:
    resource: "@YLCoreAppBundle/Resources/config/routing.yml"
    prefix:   /{_locale}/
    requirements:
        _locale: en|fr|


##FOS USER BUNDLE ROUTING

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"
    prefix:   /{_locale}/
    requirements:
      _locale: en|fr|

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix:   /{_locale}/user/profile
    requirements:
        _locale: en|fr|

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"


